#!/bin/bash
#
# This file is the automated build procedures script that is intended to be used with the
# Germantown Design or Houston AP automated build flows. It will be called within
# a clean instantiated Ubuntu VM image. The end result of this scripts should be a file
# named artifacts.tgz, which contains everything generated by the build and which will 
# be moved back to the host build machine (from the VM) for addition to a web or other 
# archive.
#
# This script must accomplish the following tasks:
#   1. Retrieve and install all dependencies, tools, etc required to complete the build
#   2. Call the project's build scripts/methods
#   3. Collect all the build/package materials and use them to create the archive.tgz file
#

# Create the artifacts directory
rm -rf artifacts
mkdir -p artifacts/output

# Step 1 - get and install dependencies and tools, etc.
./get_dependencies.sh 

# Step 2 - Run build steps
echo "Exporting release"
cd ../../
./internal_docs/scripts/export_release.sh ./internal_docs/scripts/artifacts/output
cd internal_docs/scripts/

# Step 3 - Create the artifacts.tgz archive

## Get latest commit ID and branch
export COMMIT_ID=`git log -n 1 | grep commit | grep -v 'this commit' | cut -d" " -f 2`
export git_branch=`git branch | grep '*' | cut -d" " -f 2`

## Write into the repo-revs info file
echo -n "ethfw:" > artifacts/repo-revs.txt
echo -n "${COMMIT_ID}:$git_branch" >> artifacts/repo-revs.txt
echo :`git log -1 | grep "    "` >> artifacts/repo-revs.txt

## Create a compressed tar of artifacts directory 
tar -cvzf artifacts.tgz artifacts

## Nothing past this point

