#!/bin/bash
#

WEBPATH=/var/www/targetcontent

function cleanup()
{
    # Delete the temporary path
    rm -rf ${TEMP_DIR}
}

function abort()
{
    cleanup
    exit 1
}

# Make sure to remove temp directory when script is aborted
trap abort SIGINT

# Verify that we are running this script in the correct git working tree
if [ ! -e ./ethfw_build_flags.mak ]; then
    echo "Not running in the correct path! Aborting!"
    abort
fi
if [ ! -e ./.git ]; then
    echo "Not running in a valid GIT working tree."
    abort
fi

# Read OLD (previous) release variables
source ./internal_docs/scripts/release_info.sh

echo "Package version:                  ${OLD_VERSION}"
echo "Package name:                     ${OLD_PKGNAME}"
echo "Package date:                     ${OLD_PKGDATE}"
echo "Current NDK version:              ${OLD_NDK}"
echo "Current NS version:               ${OLD_NS}"
echo "Current BIOS version (AM65XX):    ${OLD_BIOS_AM65XX}"
echo "Current BIOS version (J721E):     ${OLD_BIOS_J721E}"
echo "Current XDC version:              ${OLD_XDC}"
echo "Current GCC_ARCH64 version:       ${OLD_GCC_ARCH64}"
echo "Current CGT_ARM version (AM65XX): ${OLD_CGT_ARM_AM65XX}"
echo "Current CGT_ARM version (J721E):  ${OLD_CGT_ARM_J721E}"

# Get the output address if supplied
OUT_DIR=$1
if [ -z "${OUT_DIR}" ]; then
    OUT_DIR=.
fi
if [ ! -d ${OUT_DIR} ]; then
    echo "Invalid output directory!"
    exit 1
fi
if [ $# -eq 2 ]; then
    DO_WEB_GEN="$2"
else
    DO_WEB_GEN="n"
fi


XDC_CMD=${XDC_ROOT}/xdc
if [[ "$OSTYPE" == "cygwin" ]]; then
    # Assume cygwin
    NUM_CPUS=$(grep -c ^processor /proc/cpuinfo)
elif [[ "$OSTYPE" == "msys" ]]; then
    NUM_CPUS=$(echo $NUMBER_OF_PROCESSORS)
else
    #Assume Linux/Unix    
    NUM_CPUS=$(grep -c ^processor /proc/cpuinfo)
fi

REL_VER=${OLD_VERSION}
PKG_NAME=${OLD_PKGNAME}
PKG_TAR=${PKG_NAME}_${REL_VER}.tar
PKG_TARGZ=${PKG_TAR}.gz
TEMP_DIR=$(mktemp -d)
CURR_DIR=$(pwd)
PSDK_DIR=$(realpath ../)

mkdir -p ${TEMP_DIR}/${PKG_NAME}_${REL_VER}
if [ ! -d ${TEMP_DIR} ]; then
    echo "Could not create temporary directory!"
    exit 1
fi

# Set environment variables for build
export ETHFW_PATH=${TEMP_DIR}/${PKG_NAME}_${REL_VER}
export PSDK_PATH=${PSDK_DIR}

echo "TEMP DIR is ${TEMP_DIR}"
echo "CURR_DIR is ${CURR_DIR}"

echo "Exporting package: ${PKG_TAR}"
TAGNAME="REL.ETHFW.0${OLD_VERSION//_/.}"
git archive --format=tar ${TAGNAME} > ${TEMP_DIR}/${PKG_TAR}

pushd ${TEMP_DIR} > /dev/null
# Untar the file generated by GIT archive
tar -C ${PKG_NAME}_${REL_VER} -xf ${PKG_TAR}

# Build the library
pushd ${PKG_NAME}_${REL_VER}
make -C internal_docs/doxygen -s all
make ethfw_all
popd > /dev/null

# Remove internal_docs directory
rm -vr ${TEMP_DIR}/${PKG_NAME}_${REL_VER}/internal_docs

# Create tar.gz archive
tar -czf ${PKG_TARGZ} ${PKG_NAME}_${REL_VER}/
popd > /dev/null

# Move the archive to output directory
mv ${TEMP_DIR}/${PKG_TARGZ} ${OUT_DIR}

# Check if doing download page generation via webgen
if [[ "${DO_WEB_GEN}" == "y" ]]; then
    # Move the archive to /opt/ti directory
    cp ${OUT_DIR}/${PKG_TARGZ} /opt/ti

    # Prep the contents in the install directory
    pushd /opt/ti > /dev/null
    # Untar the image
    tar xzf ${PKG_TARGZ}
    popd > /dev/null

    # Do the download page generation
    webgen_ext ./webgen.mak ${WEBPATH} ${OUT_DIR}
    # Create symlink called 'latest'
    ln -fns ${WEBPATH}/${PKG_NAME}/${REL_VER} ${WEBPATH}/${PKG_NAME}/latest
    # Update the exports symlink created by webgen
    ln -fns /opt/ti ${WEBPATH}/${PKG_NAME}/${REL_VER}/${OUT_DIR}
fi

cleanup
exit 0
