copy /Y ..\..\trace-drivers\source\cpt2\include\* .\include\.
copy /Y ..\..\trace-drivers\source\cpt2\src\* .\src\.
copy /Y ..\..\trace-drivers\source\trace_aggr\include\* .\include\.
copy /Y ..\..\trace-drivers\source\trace_aggr\src\* .\src\.
copy /Y ..\..\trace-drivers\source\atbrep\include\* ..\k3_common\atbrep\include\.
copy /Y ..\..\trace-drivers\source\atbrep\src\* ..\k3_common\atbrep\src\.
copy /Y ..\..\trace-drivers\source\common\include\* ..\k3_common\common\include\.
copy /Y ..\..\trace-drivers\source\common\src\* ..\k3_common\common\src\.
copy /Y ..\..\trace-drivers\source\common\doc\* ..\k3_common\common\doc\.
copy /Y ..\..\trace-drivers\source\gtc\include\* ..\k3_common\gtc\include\.
copy /Y ..\..\trace-drivers\source\gtc\src\* ..\k3_common\gtc\src\.
