import json

# Load JSON inputs
def load_json(path):
    with open(path, 'r') as f:
        return json.load(f)

file_path_kw = load_json('file_path_kw.json')
report = load_json('report.json')

# Extract PR and Other files
pr_files = [entry['file'] for entry in file_path_kw]
problems = report.get('errorList', {}).get('problem', [])
other_files = sorted({p['filename'] for p in problems if p['filename'] not in pr_files})

# Severity levels
severities = [
    'Critical', 'Error', 'Warning', 'Review',
    'MISRA Mandatory', 'MISRA Required', 'MISRA Advisory',
    'HIS METRICS', 'CERT C Rule', 'CERT C Recommendation'
]

# Serialize data for embedding
pr_json = json.dumps(pr_files)
other_json = json.dumps(other_files)
prob_json = json.dumps(problems)
sev_json = json.dumps(severities)

# Build HTML

def build_html():
    html = []
    a = html.append

    # Head & Styles
    a('<!DOCTYPE html>')
    a('<html lang="en">')
    a('<head>')
    a('  <meta charset="UTF-8">')
    a('  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">')
    a('  <title>Code Analysis Dashboard</title>')
    a('  <style>')
    a('    * { margin:0; padding:0; box-sizing:border-box; }')
    a('    :root {')
    a('      --primary: #2563eb;')
    a('      --primary-dark: #1d4ed8;')
    a('      --secondary: #64748b;')
    a('      --success: #059669;')
    a('      --warning: #d97706;')
    a('      --error: #dc2626;')
    a('      --bg-primary: #ffffff;')
    a('      --bg-secondary: #f8fafc;')
    a('      --bg-tertiary: #f1f5f9;')
    a('      --text-primary: #0f172a;')
    a('      --text-secondary: #475569;')
    a('      --text-muted: #64748b;')
    a('      --border: #e2e8f0;')
    a('      --border-light: #f1f5f9;')
    a('      --shadow-sm: 0 0.67px 1.34px 0 rgb(0 0 0 / 0.05);')
    a('      --shadow: 0 0.67px 2.01px 0 rgb(0 0 0 / 0.1), 0 0.67px 1.34px -0.67px rgb(0 0 0 / 0.1);')
    a('      --shadow-lg: 0 6.7px 10.05px -2.01px rgb(0 0 0 / 0.1), 0 2.68px 4.02px -2.68px rgb(0 0 0 / 0.1);')
    a('    }')
    a('    ')
    a('    body {')
    a('      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;')
    a('      background: var(--bg-secondary);')
    a('      color: var(--text-primary);')
    a('      line-height: 1.6;font-size: 9.38px;')
    a('    }')

    # Professional card styling
    a('    .card {')
    a('      background: var(--bg-primary);')
    a('      border: 1px solid var(--border);')
    a('      border-radius: 5.36px;')
    a('      box-shadow: var(--shadow-sm);')
    a('      transition: all 0.2s ease;')
    a('    }')
    a('    .card:hover {')
    a('      box-shadow: var(--shadow);')
    a('    }')

    # Homepage styling
    a('    .homepage {')
    a('      min-height: 100vh;')
    a('      padding: 2.01rem 1.34rem;')
    a('      max-width: 804px;')
    a('      margin: 0 auto;')
    a('    }')
    a('    .homepage h1 {')
    a('      font-size: 1.675rem;')
    a('      font-weight: 700;')
    a('      color: var(--text-primary);')
    a('      margin-bottom: 0.335rem;')
    a('      text-align: center;')
    a('    }')
    a('    .homepage .subtitle {')
    a('      font-size: 0.754rem;')
    a('      color: var(--text-secondary);')
    a('      text-align: center;')
    a('      margin-bottom: 2.01rem;')
    a('    }')

    # Dashboard overview
    a('    .dashboard-overview {')
    a('      display: grid;')
    a('      grid-template-columns: repeat(auto-fit, minmax(268px, 1fr));')
    a('      gap: 1.34rem;')
    a('      margin-bottom: 2.01rem;')
    a('    }')
    a('    .overview-card {')
    a('      padding: 1.34rem;')
    a('    }')
    a('    .overview-card h2 {')
    a('      font-size: 0.838rem;')
    a('      font-weight: 600;')
    a('      color: var(--text-primary);')
    a('      margin-bottom: 1.005rem;')
    a('      display: flex;')
    a('      align-items: center;')
    a('      gap: 0.335rem;')
    a('    }')

    # Professional table styling (including summary table)
    a('    .data-table, .summary-table {')
    a('      width: 100%;')
    a('      border-collapse: collapse;')
    a('      background: var(--bg-primary);')
    a('      border-radius: 5.36px;')
    a('      overflow: hidden;')
    a('      border: 1px solid var(--border);')
    a('      margin-bottom: 1.005rem;')
    a('    }')
    a('    .data-table th, .summary-table th {')
    a('      background: var(--bg-tertiary);')
    a('      color: var(--text-primary);')
    a('      padding: 0.503rem 0.67rem;')
    a('      font-weight: 600;')
    a('      font-size: 0.586rem;')
    a('      text-align: left;')
    a('      border-bottom: 1px solid var(--border);')
    a('    }')
    a('    .data-table td, .summary-table td {')
    a('      padding: 0.503rem 0.67rem;')
    a('      border-bottom: 1px solid var(--border-light);')
    a('      font-size: 0.586rem;')
    a('    }')
    a('    .data-table tr:hover, .summary-table tr:hover {')
    a('      background: var(--bg-secondary);')
    a('    }')

    # Professional button
    a('    .btn {')
    a('      display: inline-flex;')
    a('      align-items: center;')
    a('      justify-content: center;')
    a('      padding: 0.503rem 1.005rem;')
    a('      border: none;')
    a('      border-radius: 4.02px;')
    a('      font-size: 0.586rem;')
    a('      font-weight: 500;')
    a('      cursor: pointer;')
    a('      transition: all 0.2s ease;')
    a('      text-decoration: none;')
    a('    }')
    a('    .btn-primary {')
    a('      background: var(--primary);')
    a('      color: white;')
    a('    }')
    a('    .btn-primary:hover {')
    a('      background: var(--primary-dark);')
    a('    }')
    a('    .btn-secondary {')
    a('      background: var(--bg-primary);')
    a('      color: var(--text-primary);')
    a('      border: 1px solid var(--border);')
    a('    }')
    a('    .btn-secondary:hover {')
    a('      background: var(--bg-secondary);')
    a('    }')

    # Back button styling
    a('    .back-btn {')
    a('      display: inline-flex;')
    a('      align-items: center;')
    a('      padding: 0.335rem 0.67rem;')
    a('      background: var(--bg-secondary);')
    a('      border: 1px solid var(--border);')
    a('      border-radius: 4.02px;')
    a('      color: var(--text-primary);')
    a('      font-size: 0.586rem;')
    a('      cursor: pointer;')
    a('      margin-bottom: 1.005rem;')
    a('      transition: all 0.2s ease;')
    a('    }')
    a('    .back-btn:hover {')
    a('      background: var(--bg-tertiary);')
    a('    }')

    # Analysis view layout
    a('    .analysis-view {')
    a('      display: flex;')
    a('      min-height: 100vh;')
    a('    }')
    a('    .sidebar {')
    a('      width: 214.4px;')
    a('      background: var(--bg-primary);')
    a('      border-right: 1px solid var(--border);')
    a('      padding: 1.005rem;')
    a('      overflow-y: auto;')
    a('      position: fixed;')
    a('      top: 0;')
    a('      left: 0;')
    a('      height: 100vh;')
    a('      z-index: 100;')
    a('    }')
    a('    .sidebar h3 {')
    a('      font-size: 0.67rem;')
    a('      font-weight: 600;')
    a('      color: var(--text-primary);')
    a('      margin-bottom: 0.67rem;')
    a('    }')
    a('    .sidebar h4 {')
    a('      font-size: 0.586rem;')
    a('      font-weight: 600;')
    a('      color: var(--text-primary);')
    a('      margin-bottom: 0.67rem;')
    a('    }')

    # Form controls
    a('    .form-control {')
    a('      width: 100%;')
    a('      padding: 0.335rem 0.503rem;')
    a('      border: 1px solid var(--border);')
    a('      border-radius: 4.02px;')
    a('      font-size: 0.586rem;')
    a('      transition: border-color 0.2s ease, box-shadow 0.2s ease;')
    a('    }')
    a('    .form-control:focus {')
    a('      outline: none;')
    a('      border-color: var(--primary);')
    a('      box-shadow: 0 0 0 2.01px rgb(37 99 235 / 0.1);')
    a('    }')

    # File section styling
    a('    .file-section {')
    a('      margin-bottom: 1.34rem;')
    a('      padding: 1.005rem;')
    a('      background: var(--bg-secondary);')
    a('      border-radius: 5.36px;')
    a('      border: 1px solid var(--border-light);')
    a('    }')
    a('    .file-list {')
    a('      max-height: 134px;')
    a('      overflow-y: auto;')
    a('      border: 1px solid var(--border);')
    a('      border-radius: 4.02px;')
    a('      background: var(--bg-primary);')
    a('    }')
    a('    .file-item {')
    a('      padding: 0.335rem 0.503rem;')
    a('      display: flex;')
    a('      align-items: center;')
    a('      gap: 0.335rem;')
    a('      cursor: pointer;')
    a('      border-bottom: 1px solid var(--border-light);')
    a('      font-size: 0.586rem;')
    a('    }')
    a('    .file-item:hover {')
    a('      background: var(--bg-secondary);')
    a('    }')
    a('    .file-item:last-child {')
    a('      border-bottom: none;')
    a('    }')

    # Selected files section
    a('    .selected-files {')
    a('      background: var(--bg-primary);')
    a('      border: 1px solid var(--border);')
    a('      border-radius: 5.36px;')
    a('      padding: 1.005rem;')
    a('    }')
    a('    .selected-file-tag {')
    a('      display: inline-flex;')
    a('      align-items: center;')
    a('      background: var(--bg-tertiary);')
    a('      border: 1px solid var(--border);')
    a('      border-radius: 2.68px;')
    a('      padding: 0.168rem 0.335rem;')
    a('      margin: 0.168rem 0.168rem 0.168rem 0;')
    a('      font-size: 0.503rem;')
    a('      color: var(--text-primary);')
    a('    }')
    a('    .selected-file-tag .remove {')
    a('      margin-left: 0.335rem;')
    a('      cursor: pointer;')
    a('      color: var(--error);')
    a('      font-weight: bold;')
    a('      border-radius: 50%;')
    a('      width: 10.72px;')
    a('      height: 10.72px;')
    a('      display: flex;')
    a('      align-items: center;')
    a('      justify-content: center;')
    a('      transition: background-color 0.2s ease;')
    a('    }')
    a('    .selected-file-tag .remove:hover {')
    a('      background: var(--error);')
    a('      color: white;')
    a('    }')

    # Detailed analysis button
    a('    .detailed-btn {')
    a('      background: var(--primary);')
    a('      color: white;')
    a('      border: none;')
    a('      border-radius: 4.02px;')
    a('      font-size: 0.586rem;')
    a('      font-weight: 500;')
    a('      cursor: pointer;')
    a('      transition: background-color 0.2s ease;')
    a('    }')
    a('    .detailed-btn:hover {')
    a('      background: var(--primary-dark);')
    a('    }')

    # Main content area
    a('    .main-content {')
    a('      flex: 1;')
    a('      padding: 1.34rem;')
    a('      overflow-y: auto;')
    a('      margin-left: 214.4px;')
    a('      position: relative;')
    a('    }')
    a('    .main-content h2 {')
    a('      font-size: 1.005rem;')
    a('      font-weight: 600;')
    a('      color: var(--text-primary);')
    a('      margin-bottom: 1.005rem;')
    a('    }')

    # Analysis header
    a('    .analysis-header {')
    a('      margin-bottom: 1.34rem;')
    a('    }')

    # Controls section
    a('    .controls-section {')
    a('      background: var(--bg-primary);')
    a('      padding: 1.005rem;')
    a('      border-radius: 5.36px;')
    a('      border: 1px solid var(--border);')
    a('      margin-bottom: 1.34rem;')
    a('    }')
    a('    .controls-row {')
    a('      display: flex;')
    a('      gap: 0.67rem;')
    a('      align-items: center;')
    a('      margin-bottom: 1.005rem;')
    a('      flex-wrap: wrap;')
    a('    }')
    a('    .controls-row label {')
    a('      font-size: 0.586rem;')
    a('      font-weight: 500;')
    a('      color: var(--text-primary);')
    a('      white-space: nowrap;')
    a('    }')
    a('    .controls-row select {')
    a('      min-width: 134px;')
    a('    }')

    # Filters section
    a('    .filters-section {')
    a('      border-top: 1px solid var(--border-light);')
    a('      padding-top: 1.005rem;')
    a('    }')
    a('    .filter-group {')
    a('      display: flex;')
    a('      flex-wrap: wrap;')
    a('      gap: 0.67rem;')
    a('    }')
    a('    .filter-checkbox {')
    a('      display: flex;')
    a('      align-items: center;')
    a('      gap: 0.335rem;')
    a('      padding: 0.335rem;')
    a('      background: var(--bg-secondary);')
    a('      border-radius: 4.02px;')
    a('      border: 1px solid var(--border-light);')
    a('      cursor: pointer;')
    a('      transition: background-color 0.2s ease;')
    a('    }')
    a('    .filter-checkbox:hover {')
    a('      background: var(--bg-tertiary);')
    a('    }')
    a('    .filter-checkbox input[type="checkbox"] {')
    a('      margin: 0;')
    a('    }')
    a('    .filter-checkbox label {')
    a('      font-size: 0.586rem;')
    a('      cursor: pointer;')
    a('      margin: 0;')
    a('    }')

    # Search container
    a('    .search-container {')
    a('      position: relative;')
    a('      min-width: 201px;')
    a('    }')
    a('    .search-dropdown {')
    a('      position: absolute;')
    a('      top: 100%;')
    a('      left: 0;')
    a('      right: 0;')
    a('      background: var(--bg-primary);')
    a('      border: 1px solid var(--border);')
    a('      border-top: none;')
    a('      border-radius: 0 0 4.02px 4.02px;')
    a('      max-height: 134px;')
    a('      overflow-y: auto;')
    a('      z-index: 1000;')
    a('      display: none;')
    a('      box-shadow: var(--shadow);')
    a('    }')
    a('    .search-option {')
    a('      padding: 0.335rem 0.503rem;')
    a('      cursor: pointer;')
    a('      font-size: 0.586rem;')
    a('      border-bottom: 1px solid var(--border-light);')
    a('    }')
    a('    .search-option:hover {')
    a('      background: var(--bg-secondary);')
    a('    }')
    a('    .search-option:last-child {')
    a('      border-bottom: none;')
    a('    }')

    # Issues display
    a('    .issues-container {')
    a('      background: var(--bg-primary);')
    a('      border: 1px solid var(--border);')
    a('      border-radius: 5.36px;')
    a('      overflow: hidden;')
    a('    }')
    a('    .issues-table {')
    a('      width: 100%;')
    a('      border-collapse: collapse;')
    a('    }')
    a('    .issues-table th {')
    a('      background: var(--bg-tertiary);')
    a('      padding: 0.67rem;')
    a('      font-weight: 600;')
    a('      font-size: 0.586rem;')
    a('      text-align: left;')
    a('      border-bottom: 1px solid var(--border);')
    a('      color: var(--text-primary);')
    a('    }')
    a('    .issues-table td {')
    a('      padding: 0.67rem;')
    a('      border-bottom: 1px solid var(--border-light);')
    a('      font-size: 0.586rem;')
    a('      vertical-align: top;')
    a('    }')
    a('    .issues-table tr:hover {')
    a('      background: var(--bg-secondary);')
    a('    }')

    # Severity badges
    a('    .severity-badge {')
    a('      display: inline-block;')
    a('      padding: 0.168rem 0.335rem;')
    a('      border-radius: 2.68px;')
    a('      font-size: 0.503rem;')
    a('      font-weight: 500;')
    a('      text-transform: uppercase;')
    a('      letter-spacing: 0.017em;')
    a('    }')
    a('    .severity-critical { background: #fef2f2; color: #991b1b; }')
    a('    .severity-error { background: #fef2f2; color: #dc2626; }')
    a('    .severity-warning { background: #fffbeb; color: #d97706; }')
    a('    .severity-review { background: #eff6ff; color: #2563eb; }')
    a('    .severity-misra { background: #f3e8ff; color: #7c3aed; }')
    a('    .severity-his { background: #ecfdf5; color: #059669; }')
    a('    .severity-cert { background: #fff7ed; color: #ea580c; }')

    # Responsive design
    a('    @media (max-width: 1024px) {')
    a('      .dashboard-overview { grid-template-columns: 1fr; }')
    a('      .analysis-view { flex-direction: column; }')
    a('      .sidebar { ')
    a('        position: relative; ')
    a('        width: 100%; ')
    a('        max-height: 268px; ')
    a('        height: auto;')
    a('      }')
    a('      .main-content { margin-left: 0; }')
    a('    }')
    a('    @media (max-width: 768px) {')
    a('      .homepage { padding: 1.34rem 0.67rem; }')
    a('      .homepage h1 { font-size: 1.34rem; }')
    a('      .controls-row { flex-direction: column; align-items: stretch; }')
    a('      .controls-row > * { width: 100%; }')
    a('      .filter-group { flex-direction: column; }')
    a('      .main-content { padding: 0.67rem; }')
    a('      .sidebar { padding: 0.67rem; }')
    a('    }')

    # Utility classes
    a('    .hidden { display: none !important; }')
    a('    .text-center { text-align: center; }')
    a('    .mb-1 { margin-bottom: 0.335rem; }')
    a('    .mb-2 { margin-bottom: 0.67rem; }')
    a('    .mb-3 { margin-bottom: 1.005rem; }')
    a('    .flex { display: flex; }')
    a('    .flex-1 { flex: 1; }')
    a('    .gap-2 { gap: 0.335rem; }')

    a('    .go-to-top {')
    a('      position: fixed;')
    a('      bottom: 1.34rem;')
    a('      right: 1.34rem;')
    a('      width: 33.5px;')
    a('      height: 33.5px;')
    a('      background: var(--primary);')
    a('      color: white;')
    a('      border: none;')
    a('      border-radius: 50%;')
    a('      cursor: pointer;')
    a('      font-size: 0.804rem;')
    a('      box-shadow: var(--shadow-lg);')
    a('      transition: all 0.3s ease;')
    a('      z-index: 1000;')
    a('      opacity: 0;')
    a('      visibility: hidden;')
    a('    }')
    a('    .go-to-top.visible {')
    a('      opacity: 1;')
    a('      visibility: visible;')
    a('    }')
    a('    .go-to-top:hover {')
    a('      background: var(--primary-dark);')
    a('      transform: translateY(-1.34px);')
    a('    }')

    a('    .theme-toggle {')
    a('      position: fixed;')
    a('      top: 1.34rem;')
    a('      right: 1.34rem;')
    a('      width: 33.5px;')
    a('      height: 33.5px;')
    a('      background: var(--bg-primary);')
    a('      border: 1.34px solid var(--border);')
    a('      border-radius: 50%;')
    a('      cursor: pointer;')
    a('      display: flex;')
    a('      align-items: center;')
    a('      justify-content: center;')
    a('      font-size: 1.005rem;')
    a('      transition: all 0.3s ease;')
    a('      z-index: 1001;')
    a('      box-shadow: var(--shadow);')
    a('    }')
    a('    .theme-toggle:hover {')
    a('      transform: scale(1.1);')
    a('      box-shadow: var(--shadow-lg);')
    a('    }')
    a('  </style>')
    a('</head>')

    # Body
    a('<body>')

    a('<body>')
    a('  <div class="homepage" id="homepage">')
    a('    <div class="text-center mb-3">')
    a('      <h1>Code Analysis Dashboard</h1>')
    a('      <p class="subtitle">Comprehensive analysis of code quality issues across your project files</p>')
    a('    </div>')
    
    a('    <div class="dashboard-overview">')
    a('      <div class="overview-card card">')
    a('        <h2>📁 PR Files Analysis</h2>')
    a('        <table class="data-table" id="prOverviewTable">')
    a('          <thead><tr><th>Severity</th><th>Count</th></tr></thead>')
    a('          <tbody></tbody>')
    a('        </table>')
    a('      </div>')
    
    a('      <div class="overview-card card">')
    a('        <h2>📂 Other Files Analysis</h2>')
    a('        <table class="data-table" id="otherOverviewTable">')
    a('          <thead><tr><th>Severity</th><th>Count</th></tr></thead>')
    a('          <tbody></tbody>')
    a('        </table>')
    a('      </div>')
    a('    </div>')
    
    a('    <div class="text-center">')
    a('      <button class="btn btn-primary" onclick="showDetailedAnalysis()">📊 View Detailed Analysis</button>')
    a('    </div>')
    a('  </div>')
    # Analysis View
    a('  <div class="analysis-view hidden" id="analysisView">')
    # Sidebar
    a('    <div class="sidebar">')
    a('      <button class="back-btn" onclick="showHomepage()">&larr; Back to Home</button>')
    
    a('      <div class="file-section">')
    a('        <h3>PR Files</h3>')
    a('        <div class="flex gap-2 mb-2">')
    a('          <button class="btn btn-secondary flex-1" onclick="selectAllFiles(\'pr\', true)">Select All</button>')
    a('          <button class="btn btn-secondary flex-1" onclick="selectAllFiles(\'pr\', false)">Deselect All</button>')
    a('        </div>')
    a('        <input type="text" class="form-control mb-2" id="prSearch" placeholder="Search PR files... (Press Enter to select matching)" oninput="filterFiles(\'pr\')" onkeypress="handleSearchKeyPress(event, \'pr\')">')
    a('        <div class="file-list" id="prFileList"></div>')
    a('      </div>')

    a('      <div class="file-section">')
    a('        <h3>Other Files</h3>')
    a('        <div class="flex gap-2 mb-2">')
    a('          <button class="btn btn-secondary flex-1" onclick="selectAllFiles(\'other\', true)">Select All</button>')
    a('          <button class="btn btn-secondary flex-1" onclick="selectAllFiles(\'other\', false)">Deselect All</button>')
    a('        </div>')
    a('        <input type="text" class="form-control mb-2" id="otherSearch" placeholder="Search other files... (Press Enter to select matching)" oninput="filterFiles(\'other\')" onkeypress="handleSearchKeyPress(event, \'other\')">')
    a('        <div class="file-list" id="otherFileList"></div>')
    a('      </div>')
    
    a('      <div class="selected-files">')
    a('        <h4>Selected Files (<span id="selectedCount">0</span>)</h4>')
    a('        <div id="selectedFileTags"></div>')
    a('        <button class="detailed-btn" style="width:100%; margin-top:15px; padding:10px;" onclick="analyzeSelectedFiles()">Analyze Selected</button>')
    a('      </div>')
    a('    </div>')

    # Main Content
    a('    <div class="main-content">')
    a('      <div class="analysis-header">')
    a('        <h2 id="analysisTitle">Select files to analyze</h2>')
    a('        <table class="summary-table" id="summaryTable" style="display:none;">')
    a('          <thead><tr><th>Severity</th><th>Count</th></tr></thead>')
    a('          <tbody></tbody>')
    a('        </table>')
    a('      </div>')
    
    a('      <div class="controls-section" id="controlsSection" style="display:none;">')
    a('        <div class="controls-row">')
    a('          <label>Sort by:</label>')
    a('          <select id="sortSelect" onchange="handleSortChange()">')
    a('            <option value="">--Select Field--</option>')
    a('            <option value="problemID">Problem ID</option>')
    a('            <option value="line">Line</option>')
    a('            <option value="severity">Severity</option>')
    a('            <option value="code">Code</option>')
    a('            <option value="citingStatus">Citing Status</option>')
    a('            <option value="displayAs">Display As</option>')
    a('            <option value="message">Message</option>')
    a('          </select>')
    
    a('          <label>Search:</label>')
    a('          <div class="search-container">')
    a('            <input id="searchInput" placeholder="Select a field to search..." disabled oninput="renderIssues()">')
    a('            <div id="searchDropdown" class="search-dropdown"></div>')
    a('          </div>')
    a('        </div>')
    
    a('        <div class="filters-section">')
    a('          <label style="display:block; margin-bottom:10px; font-weight:600; color:#2c3e50;">Filter by Severity:</label>')
    a('          <div class="filter-group" id="severityFilters"></div>')
    a('        </div>')
    a('      </div>')
    
    a('      <div class="issues-grid" id="issuesGrid"></div>')
    a('    </div>')
    a('  </div>')
    a('  <button class="go-to-top" id="goToTopBtn" onclick="scrollToTop()" title="Go to top">↑</button>')

    a('</body>')

    # JavaScript
    a('<script>')
    a('  const prFiles = ' + pr_json + ';')
    a('  const otherFiles = ' + other_json + ';')
    a('  const problems = ' + prob_json + ';')
    a('  const severities = ' + sev_json + ';')
    
    a('  let selectedFiles = new Set();')
    a('  let activeFilters = new Set(severities);')
    a('  let searchableValues = new Set();')
    a('  let currentAnalysisProblems = [];')

    # Initialize
    a('  function init() {')
    a('    renderHomepage();')
    a('    initializeFileLists();')
    a('    setupSearch();')
    a('  }')

    # Homepage functions
    a('  function renderHomepage() {')
    a('    fillOverviewTable("prOverviewTable", prFiles);')
    a('    fillOverviewTable("otherOverviewTable", otherFiles);')
    a('  }')
    
    a('  function fillOverviewTable(tableId, files) {')
    a('    const counts = Object.fromEntries(severities.map(s => [s, 0]));')
    a('    problems.filter(p => files.includes(p.filename)).forEach(p => counts[p.severity]++);')
    a('    const tbody = document.getElementById(tableId).querySelector("tbody");')
    a('    tbody.innerHTML = "";')
    a('    severities.forEach(severity => {')
    a('        const row = tbody.insertRow();')
    a('        row.insertCell().textContent = severity;')
    a('        row.insertCell().textContent = counts[severity];')
    a('    });')
    a('  }')

    # Navigation functions
    a('  function showDetailedAnalysis() {')
    a('    document.getElementById("homepage").classList.add("hidden");')
    a('    document.getElementById("analysisView").classList.remove("hidden");')
    a('  }')
    
    a('  function showHomepage() {')
    a('    document.getElementById("analysisView").classList.add("hidden");')
    a('    document.getElementById("homepage").classList.remove("hidden");')
    a('    selectedFiles.clear();')
    a('    updateSelectedFilesDisplay();')
    a('    resetAnalysis();')
    a('    document.querySelectorAll(\'input[type="checkbox"]\').forEach(checkbox => {')
    a('      checkbox.checked = false;')
    a('    });')
    a('    // Re-render file lists to ensure clean state')
    a('    initializeFileLists();')
    a('  }')

    # File list functions
    a('  function initializeFileLists() {')
    a('    renderFileList("prFileList", prFiles, "pr");')
    a('    renderFileList("otherFileList", otherFiles, "other");')
    a('  }')
    
    a('  function renderFileList(containerId, files, type) {')
    a('    const container = document.getElementById(containerId);')
    a('    container.innerHTML = "";')
    a('    files.forEach(file => {')
    a('      const item = document.createElement("div");')
    a('      item.className = "file-item";')
    a('      item.innerHTML = `<input type="checkbox" id="${type}_${file}" onchange="toggleFileSelection(\'${file}\')"> ${file}`;')
    a('      container.appendChild(item);')
    a('    });')
    a('  }')
    
    a('  function filterFiles(type) {')
    a('    const searchValue = document.getElementById(type + "Search").value.toLowerCase();')
    a('    const files = type === "pr" ? prFiles : otherFiles;')
    a('    const container = document.getElementById(type + "FileList");')
    a('    ')
    a('    container.innerHTML = "";')
    a('    const filteredFiles = files.filter(file => file.toLowerCase().includes(searchValue));')
    a('    ')
    a('    filteredFiles.forEach(file => {')
    a('      const item = document.createElement("div");')
    a('      item.className = "file-item";')
    a('      const isSelected = selectedFiles.has(file);')
    a('      item.innerHTML = `<input type="checkbox" ${isSelected ? "checked" : ""} id="${type}_${file}" onchange="toggleFileSelection(\'${file}\')"> ${file}`;')
    a('      container.appendChild(item);')
    a('    });')
    a('  }')

    a('  function handleSearchKeyPress(event, type) {')
    a('    if (event.key === "Enter") {')
    a('      event.preventDefault();')
    a('      const searchValue = event.target.value.toLowerCase();')
    a('      if (searchValue.trim() === "") return;')
    a('      ')
    a('      const files = type === "pr" ? prFiles : otherFiles;')
    a('      const matchingFiles = files.filter(file => file.toLowerCase().includes(searchValue));')
    a('      ')
    a('      // Select all matching files')
    a('      matchingFiles.forEach(file => {')
    a('        selectedFiles.add(file);')
    a('        const checkbox = document.getElementById(`${type}_${file}`);')
    a('        if (checkbox) {')
    a('          checkbox.checked = true;')
    a('        }')
    a('      });')
    a('      ')
    a('      updateSelectedFilesDisplay();')
    a('      ')
    a('      // Show feedback')
    a('      if (matchingFiles.length > 0) {')
    a('        event.target.style.borderColor = "var(--success)";')
    a('        setTimeout(() => {')
    a('          event.target.style.borderColor = "";')
    a('        }, 1000);')
    a('      }')
    a('    }')
    a('  }')

    a('  function toggleFileSelection(file) {')
    a('    if (selectedFiles.has(file)) {')
    a('      selectedFiles.delete(file);')
    a('    } else {')
    a('      selectedFiles.add(file);')
    a('    }')
    a('    updateSelectedFilesDisplay();')
    a('  }')
    
    a('  function updateSelectedFilesDisplay() {')
    a('    const container = document.getElementById("selectedFileTags");')
    a('    const countElement = document.getElementById("selectedCount");')
    a('    ')
    a('    countElement.textContent = selectedFiles.size;')
    a('    container.innerHTML = "";')
    a('    ')
    a('    selectedFiles.forEach(file => {')
    a('      const tag = document.createElement("span");')
    a('      tag.className = "selected-file-tag";')
    a('      tag.innerHTML = `${file} <span class="remove" onclick="removeFileSelection(\'${file}\')">&times;</span>`;')
    a('      container.appendChild(tag);')
    a('    });')
    a('  }')
    
    a('  function removeFileSelection(file) {')
    a('    selectedFiles.delete(file);')
    a('    updateSelectedFilesDisplay();')
    a('    // Update checkboxes')
    a('    const prCheckbox = document.getElementById(`pr_${file}`);')
    a('    const otherCheckbox = document.getElementById(`other_${file}`);')
    a('    if (prCheckbox) prCheckbox.checked = false;')
    a('    if (otherCheckbox) otherCheckbox.checked = false;')
    a('  }')

    # Analysis functions
    a('  function analyzeSelectedFiles() {')
    a('    if (selectedFiles.size === 0) {')
    a('      alert("Please select at least one file to analyze.");')
    a('      return;')
    a('    }')
    a('    ')
    a('    currentAnalysisProblems = problems.filter(p => selectedFiles.has(p.filename));')
    a('    ')
    a('    const title = document.getElementById("analysisTitle");')
    a('    title.textContent = `Analysis Results (${selectedFiles.size} files selected)`;')
    a('    ')
    a('    renderSummaryTable();')
    a('    initializeSeverityFilters();')
    a('    resetSearchAndSort();')
    a('    renderIssues();')
    a('    ')
    a('    document.getElementById("summaryTable").style.display = "table";')
    a('    document.getElementById("controlsSection").style.display = "block";')
    a('  }')
    
    a('  function renderSummaryTable() {')
    a('    const counts = Object.fromEntries(severities.map(s => [s, 0]));')
    a('    currentAnalysisProblems.forEach(p => counts[p.severity]++);')
    a('    ')
    a('    const tbody = document.getElementById("summaryTable").querySelector("tbody");')
    a('    tbody.innerHTML = "";')
    a('    ')
    a('    severities.forEach(severity => {')
    a('      if (counts[severity] > 0) {')
    a('        const row = tbody.insertRow();')
    a('        row.insertCell().textContent = severity;')
    a('        row.insertCell().textContent = counts[severity];')
    a('      }')
    a('    });')
    a('  }')
    
    a('  function initializeSeverityFilters() {')
    a('    const container = document.getElementById("severityFilters");')
    a('    container.innerHTML = "";')
    a('    activeFilters = new Set(severities);')
    a('    ')
    a('    severities.forEach(severity => {')
    a('      const hasIssues = currentAnalysisProblems.some(p => p.severity === severity);')
    a('      if (hasIssues) {')
    a('        const wrapper = document.createElement("div");')
    a('        wrapper.className = "filter-checkbox";')
    a('        wrapper.innerHTML = `<input type="checkbox" id="filter_${severity}" checked onchange="toggleSeverityFilter(\'${severity}\')"> <label for="filter_${severity}">${severity}</label>`;')
    a('        container.appendChild(wrapper);')
    a('      }')
    a('    });')
    a('  }')
    
    a('  function toggleSeverityFilter(severity) {')
    a('    if (activeFilters.has(severity)) {')
    a('      activeFilters.delete(severity);')
    a('    } else {')
    a('      activeFilters.add(severity);')
    a('    }')
    a('    renderIssues();')
    a('  }')

    # Search and sort functions
    a('  function setupSearch() {')
    a('    const searchInput = document.getElementById("searchInput");')
    a('    const dropdown = document.getElementById("searchDropdown");')
    a('    ')
    a('    searchInput.addEventListener("focus", function() {')
    a('      if (searchableValues.size > 0) {')
    a('        showSearchDropdown(this.value.toLowerCase());')
    a('      }')
    a('    });')
    a('    ')
    a('    document.addEventListener("click", function(e) {')
    a('      if (!e.target.closest(".search-container")) {')
    a('        hideSearchDropdown();')
    a('      }')
    a('    });')
    a('  }')
    
    a('  function handleSortChange() {')
    a('    const selectedField = document.getElementById("sortSelect").value;')
    a('    const searchInput = document.getElementById("searchInput");')
    a('    ')
    a('    if (selectedField && currentAnalysisProblems.length > 0) {')
    a('      collectSearchableValues(selectedField);')
    a('      searchInput.placeholder = `Search in ${selectedField}...`;')
    a('      searchInput.disabled = false;')
    a('    } else {')
    a('      searchableValues.clear();')
    a('      searchInput.placeholder = "Select a field to search...";')
    a('      searchInput.disabled = true;')
    a('    }')
    a('    ')
    a('    searchInput.value = "";')
    a('    hideSearchDropdown();')
    a('    renderIssues();')
    a('  }')
    
    a('  function collectSearchableValues(field) {')
    a('    searchableValues.clear();')
    a('    currentAnalysisProblems.forEach(p => {')
    a('      const value = p[field];')
    a('      if (value !== null && value !== undefined && value !== "") {')
    a('        searchableValues.add(String(value));')
    a('      }')
    a('    });')
    a('  }')
    
    a('  function showSearchDropdown(query) {')
    a('    const dropdown = document.getElementById("searchDropdown");')
    a('    dropdown.innerHTML = "";')
    a('    ')
    a('    let filteredValues = Array.from(searchableValues);')
    a('    if (query) {')
    a('      filteredValues = filteredValues.filter(value => value.toLowerCase().includes(query));')
    a('    }')
    a('    ')
    a('    filteredValues = [...new Set(filteredValues)].sort().slice(0, 50);')
    a('    ')
    a('    filteredValues.forEach(value => {')
    a('      const option = document.createElement("div");')
    a('      option.className = "search-option";')
    a('      option.textContent = value;')
    a('      option.addEventListener("click", function() {')
    a('        document.getElementById("searchInput").value = value;')
    a('        hideSearchDropdown();')
    a('        renderIssues();')
    a('      });')
    a('      dropdown.appendChild(option);')
    a('    });')
    a('    ')
    a('    dropdown.style.display = filteredValues.length > 0 ? "block" : "none";')
    a('  }')
    
    a('  function hideSearchDropdown() {')
    a('    document.getElementById("searchDropdown").style.display = "none";')
    a('  }')
    
    a('  function resetSearchAndSort() {')
    a('    document.getElementById("sortSelect").value = "";')
    a('    document.getElementById("searchInput").value = "";')
    a('    document.getElementById("searchInput").disabled = true;')
    a('    document.getElementById("searchInput").placeholder = "Select a field to search...";')
    a('    searchableValues.clear();')
    a('    hideSearchDropdown();')
    a('  }')
    
    a('  function resetAnalysis() {')
    a('    document.getElementById("summaryTable").style.display = "none";')
    a('    document.getElementById("controlsSection").style.display = "none";')
    a('    document.getElementById("analysisTitle").textContent = "Select files to analyze";')
    a('    document.getElementById("issuesGrid").innerHTML = "";')
    a('    currentAnalysisProblems = [];')
    a('  }')

    # Render issues
    a('  function renderIssues() {')
    a('    const container = document.getElementById("issuesGrid");')
    a('    container.innerHTML = "";')
    a('    ')
    a('    let filteredProblems = currentAnalysisProblems.filter(p => activeFilters.has(p.severity));')
    a('    ')
    a('    const query = document.getElementById("searchInput").value.toLowerCase();')
    a('    if (query) {')
    a('      const selectedField = document.getElementById("sortSelect").value;')
    a('      if (selectedField) {')
    a('        filteredProblems = filteredProblems.filter(p => String(p[selectedField]).toLowerCase().includes(query));')
    a('      }')
    a('    }')
    a('    ')
    a('    const sortKey = document.getElementById("sortSelect").value;')
    a('    if (sortKey) {')
    a('      filteredProblems.sort((a, b) => {')
    a('        if (sortKey === "line") {')
    a('          return parseInt(a[sortKey]) - parseInt(b[sortKey]);')
    a('        }')
    a('        if (a[sortKey] < b[sortKey]) return -1;')
    a('        if (a[sortKey] > b[sortKey]) return 1;')
    a('        return 0;')
    a('      });')
    a('    }')
    a('    ')
    a('    if (filteredProblems.length === 0) {')
    a('      container.innerHTML = `')
    a('        <div style="text-align:center; padding: 3rem; color: var(--text-muted);">')
    a('          <div style="font-size: 3rem; margin-bottom: 1rem;">🔍</div>')
    a('          <h3 style="margin-bottom: 0.5rem;">No issues found</h3>')
    a('          <p>Try adjusting your filters or search criteria</p>')
    a('        </div>`;')
    a('      return;')
    a('    }')
    a('    ')
    a('    const table = document.createElement("div");')
    a('    table.className = "issues-container";')
    a('    table.innerHTML = `')
    a('      <table class="issues-table">')
    a('        <thead>')
    a('          <tr>')
    a('            <th style="width: 80px;">ID</th>')
    a('            <th style="width: 300px;">File</th>')
    a('            <th style="width: 80px;">Line</th>')
    a('            <th style="width: 120px;">Severity</th>')
    a('            <th style="width: 100px;">Code</th>')
    a('            <th>Message</th>')
    a('          </tr>')
    a('        </thead>')
    a('        <tbody id="issuesTableBody">')
    a('        </tbody>')
    a('      </table>`;')
    a('    ')
    a('    container.appendChild(table);')
    a('    ')
    a('    const tbody = document.getElementById("issuesTableBody");')
    a('    filteredProblems.forEach(problem => {')
    a('      const row = document.createElement("tr");')
    a('      ')
    a('      const severityClass = getSeverityClass(problem.severity);')
    a('      ')
    a('      row.innerHTML = `')
    a('        <td><strong>#${problem.problemID}</strong></td>')
    a('        <td><code>${problem.filename}</code></td>')
    a('        <td>${problem.line}</td>')
    a('        <td><span class="severity-badge ${severityClass}">${problem.severity}</span></td>')
    a('        <td><code>${problem.code || "N/A"}</code></td>')
    a('        <td>${problem.message}</td>')
    a('      `;')
    a('      ')
    a('      tbody.appendChild(row);')
    a('    });')
    a('  }')
    a('  ')
    a('  function getSeverityClass(severity) {')
    a('    const classMap = {')
    a('      "Critical": "severity-critical",')
    a('      "Error": "severity-error",')
    a('      "Warning": "severity-warning",')
    a('      "Review": "severity-review",')
    a('      "MISRA Mandatory": "severity-misra",')
    a('      "MISRA Required": "severity-misra",')
    a('      "MISRA Advisory": "severity-misra",')
    a('      "HIS METRICS": "severity-his",')
    a('      "CERT C Rule": "severity-cert",')
    a('      "CERT C Recommendation": "severity-cert"')
    a('    };')
    a('    return classMap[severity] || "severity-review";')
    a('  }')
    a('  function getSeverityColor(severity) {')
    a('    const colors = {')
    a('      "Critical": "#dc2626",')
    a('      "Error": "#ef4444",')
    a('      "Warning": "#f59e0b",')
    a('      "Review": "#3b82f6",')
    a('      "MISRA Mandatory": "#8b5cf6",')
    a('      "MISRA Required": "#a855f7",')
    a('      "MISRA Advisory": "#06b6d4",')
    a('      "HIS METRICS": "#10b981",')
    a('      "CERT C Rule": "#f97316",')
    a('      "CERT C Recommendation": "#84cc16"')
    a('    };')
    a('    return colors[severity] || "#6b7280";')
    a('  }')
    a('  function selectAllFiles(type, select) {')
    a('    const files = type === "pr" ? prFiles : otherFiles;')
    a('    files.forEach(file => {')
    a('      if (select) {')
    a('        selectedFiles.add(file);')
    a('      } else {')
    a('        selectedFiles.delete(file);')
    a('      }')
    a('      const checkbox = document.getElementById(`${type}_${file}`);')
    a('      if (checkbox) {')
    a('        checkbox.checked = select;')
    a('      }')
    a('    });')
    a('    updateSelectedFilesDisplay();')
    a('  }')
    a('  // Go to top functionality')
    a('  function scrollToTop() {')
    a('    window.scrollTo({ top: 0, behavior: "smooth" });')
    a('  }')
    a('  ')
    a('  window.addEventListener("scroll", function() {')
    a('    const goToTopBtn = document.getElementById("goToTopBtn");')
    a('    if (window.pageYOffset > 300) {')
    a('      goToTopBtn.classList.add("visible");')
    a('    } else {')
    a('      goToTopBtn.classList.remove("visible");')
    a('    }')
    a('  });')
    a('  ')
    a('  // Theme functionality')
    a('  window.onload = init;')
    a('</script>')
    a('</html>')

    return "\n".join(html)

if __name__=='__main__':
    with open('results.html','w',encoding='utf-8') as f:
        f.write(build_html())
    print("kw.html generated successfully.")